[package]
name = "wasmboy"
version = "0.0.1"
description = "Game Boy / Game Boy Color Emulator Library, 🎮written for WebAssembly using AssemblyScript. 🚀Built for Wasmer using the Experimental I/O Devices!"
license = "GPL-3.0"
repository = "https://github.com/torch2424/wasmboy"

[[module]]
name = "wasmboy-wasmer"
source = "../../dist/wasmer/wasmboy-wasmer.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.0.0-unstable"

[[command]]
name = "wasmboy"
module = "wasmboy"
